(function(){'use strict';
const $=id=>document.getElementById(id),packs=window.PENGUIN_PACKS,audio=new PenguinAudio(),renderer=new PenguinRenderer($('board')),directions={U:[0,-1],D:[0,1],L:[-1,0],R:[1,0]},storageKey='penguinpush-v2';
let packIndex=0,index=0,character=0,theme='ice',completed={},game,busy=false,pending=[],animationTimer=null,pressTimer=null,zoom=1;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');const p=packs.findIndex(p=>p.id===saved.pack);packIndex=p<0?0:p;index=Math.max(0,Math.min(packs[packIndex].levels.length-1,Number.isInteger(saved.index)?saved.index:0));character=saved.character===1?1:0;theme=['ice','night','wood'].includes(saved.theme)?saved.theme:'ice';if(saved.completed&&typeof saved.completed==='object')completed=saved.completed;audio.enabled=saved.sound!==false;audio.volume=typeof saved.volume==='number'&&Number.isFinite(saved.volume)?Math.max(0,Math.min(1,saved.volume)):.35;}catch{}
function save(){try{localStorage.setItem(storageKey,JSON.stringify({pack:packs[packIndex].id,index,character,theme,completed,sound:audio.enabled,volume:audio.volume}));}catch{}}
function options(){const pack=packs[packIndex];$('pack').innerHTML=packs.map((p,i)=>`<option value="${i}">${p.name} · ${p.levels.length}</option>`).join('');$('pack').value=packIndex;$('level').innerHTML=pack.levels.map((l,i)=>`<option value="${i}">${completed[l.id]?'✓ ':''}${String(i+1).padStart(2,'0')} · ${l.name}</option>`).join('');$('level').value=index;const n=pack.levels.filter(l=>completed[l.id]).length;$('progress').textContent=`${n} de ${pack.levels.length} niveles completados en esta colección.`;}
function update(){const pack=packs[packIndex];$('title').textContent=pack.levels[index].name;$('subtitle').textContent=`${pack.name} · ${index+1} de ${pack.levels.length}`;$('moves').textContent=game.moves;$('pushes').textContent=game.pushes;$('placed').textContent=[...game.boxes].filter(k=>game.goals.has(k)).length+'/'+game.goals.size;$('undo').disabled=!game.history.length;$('mobileUndo').disabled=!game.history.length;$('prev').disabled=index===0;$('forward').disabled=index===pack.levels.length-1;$('status').textContent=game.won?'¡Pedido completo! Puedes deshacer o avanzar al siguiente nivel.':game.cornerBlocked?'Una caja está atrapada en una esquina. Pulsa Deshacer para recuperarla.':'Empuja las cajas hasta las marcas. Cuidado con las esquinas.';}
function center(){const v=$('viewport');v.scrollLeft=(v.scrollWidth-v.clientWidth)/2;v.scrollTop=Math.max(0,(v.scrollHeight-v.clientHeight)/2);}
function cancel(){clearTimeout(animationTimer);busy=false;pending=[];}
function load(i){cancel();index=Math.max(0,Math.min(packs[packIndex].levels.length-1,i));game=new PenguinSokoban(packs[packIndex].levels[index]);$('win').hidden=true;renderer.setGame(game);options();update();save();requestAnimationFrame(center);}
function victory(){const level=packs[packIndex].levels[index],previous=completed[level.id],best=previous?.moves??Infinity;completed[level.id]={moves:Math.min(best,game.moves),pushes:Math.min(previous?.pushes??Infinity,game.pushes)};save();options();renderer.celebrate();audio.play('win');$('winText').textContent=`${game.moves} pasos · ${game.pushes} empujes. `+(index===packs[packIndex].levels.length-1?'¡Has completado el último nivel de la colección!':'El siguiente pedido te espera.');$('next').textContent=index===packs[packIndex].levels.length-1?'Volver al primer nivel':'Siguiente nivel →';$('win').hidden=false;$('win').scrollIntoView({block:'center',behavior:renderer.reducedMotion?'auto':'smooth'});$('next').focus({preventScroll:true});}
function move(direction){if(!$('welcome').hidden||!$('settings').hidden)return;if(!directions[direction]||!$('win').hidden||game.won)return;audio.activate();if(busy){if(pending.length<3)pending.push(direction);return;}const event=game.move(...directions[direction]);if(event.type==='blocked'){audio.play('blocked');renderer.draw(performance.now());return;}if(event.type==='finished')return;audio.play(event.box?.delivered?'goal':event.type);renderer.animate(event);update();busy=true;animationTimer=setTimeout(()=>{busy=false;if(event.won){pending=[];victory();}else if(pending.length)move(pending.shift());},renderer.reducedMotion?0:event.type==='push'?185:145);}
function undo(){cancel();if(game.undo()){audio.play('undo');$('win').hidden=true;renderer.setGame(game);update();}}
function soundUI(){$('sound').setAttribute('aria-pressed',String(audio.enabled));$('sound').setAttribute('aria-label',audio.enabled?'Silenciar sonidos':'Activar sonidos');$('sound').textContent=audio.enabled?'♫ Sonido':'♫ Silenciado';$('volume').value=Math.round(audio.volume*100);$('volumeText').textContent=Math.round(audio.volume*100)+'%';}
function selectCharacter(c){character=c;renderer.character=c;$('blue').setAttribute('aria-pressed',String(c===0));$('pink').setAttribute('aria-pressed',String(c===1));$('chooseBlue').setAttribute('aria-pressed',String(c===0));$('choosePink').setAttribute('aria-pressed',String(c===1));renderer.draw(performance.now());save();}
$('chooseBlue').onclick=()=>selectCharacter(0);$('choosePink').onclick=()=>selectCharacter(1);
function modal(id,open){$(id).hidden=!open;document.body.classList.toggle('modal-open',!$('welcome').hidden||!$('settings').hidden);$('board').inert=!$('welcome').hidden||!$('settings').hidden;}
$('play').onclick=()=>{audio.activate();modal('welcome',false);$('board').focus({preventScroll:true});resizeBoard();};$('settingsOpen').onclick=()=>{stopPress();pending=[];modal('settings',true);$('settingsClose').focus();};$('settingsClose').onclick=()=>{modal('settings',false);$('settingsOpen').focus();};
$('sound').onclick=()=>{audio.setEnabled(!audio.enabled);if(audio.enabled)audio.play('goal');soundUI();save();};$('volume').oninput=e=>{audio.volume=Number(e.target.value)/100;soundUI();save();};$('volume').onchange=()=>audio.play('goal');$('blue').onclick=()=>selectCharacter(0);$('pink').onclick=()=>selectCharacter(1);$('theme').onchange=e=>{theme=e.target.value;renderer.theme=theme;document.body.dataset.theme=theme;renderer.draw(performance.now());save();};$('pack').onchange=e=>{packIndex=Number(e.target.value);load(0);};$('level').onchange=e=>load(Number(e.target.value));$('undo').onclick=undo;$('mobileUndo').onclick=undo;$('reset').onclick=()=>load(index);$('prev').onclick=()=>index>0&&load(index-1);$('forward').onclick=()=>index<packs[packIndex].levels.length-1&&load(index+1);$('next').onclick=()=>load(index===packs[packIndex].levels.length-1?0:index+1);$('review').onclick=()=>{$('win').hidden=true;};$('zoom').onchange=e=>{zoom=Number(e.target.value);$('board').style.width=(100*zoom)+'%';$('viewport').classList.toggle('zoomed',zoom>1);requestAnimationFrame(center);};
document.addEventListener('keydown',e=>{if(!$('welcome').hidden||!$('settings').hidden){if(e.key==='Escape'&&$('welcome').hidden)$('settingsClose').click();return;}if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;const direction={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R',w:'U',s:'D',a:'L',d:'R'}[e.key]||{W:'U',S:'D',A:'L',D:'R'}[e.key];if(direction){e.preventDefault();move(direction);}else if(e.key.toLowerCase()==='z'){e.preventDefault();undo();}else if(e.key.toLowerCase()==='r'){e.preventDefault();load(index);}});
// Touch buttons repeat while held, and always stop on release/cancel/background.
function stopPress(){clearTimeout(pressTimer);pressTimer=null;}
document.querySelectorAll('[data-dir]').forEach(button=>{let pointerUsed=false;button.addEventListener('pointerdown',e=>{e.preventDefault();pointerUsed=true;button.setPointerCapture(e.pointerId);stopPress();move(button.dataset.dir);const repeat=()=>{move(button.dataset.dir);pressTimer=setTimeout(repeat,190);};pressTimer=setTimeout(repeat,300);});for(const name of['pointerup','pointercancel','lostpointercapture'])button.addEventListener(name,stopPress);button.addEventListener('click',()=>{if(!pointerUsed)move(button.dataset.dir);pointerUsed=false;});});
let start=null;
function swipe(e){if(!start)return;const dx=e.clientX-start[0],dy=e.clientY-start[1],threshold=24;if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;move(Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');start=[e.clientX,e.clientY];}
$('board').addEventListener('pointerdown',e=>{if(zoom>1||!$('welcome').hidden||!$('settings').hidden)return;start=[e.clientX,e.clientY];$('board').setPointerCapture(e.pointerId);});$('board').addEventListener('pointermove',swipe);$('board').addEventListener('pointerup',e=>{swipe(e);start=null;});for(const name of ['pointercancel','lostpointercapture'])$('board').addEventListener(name,()=>{start=null;});
function resizeBoard(){const width=$('viewport').clientWidth||innerWidth;const available=Math.max(220,innerHeight-$('stage').getBoundingClientRect().top-190);renderer.canvas.width=900;renderer.canvas.height=Math.round(Math.max(420,Math.min(1100,900*available/width)));renderer.draw(performance.now());}
window.addEventListener('resize',resizeBoard);
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPress();pending=[];audio.pause();}});window.addEventListener('blur',stopPress);
// Small native lifecycle bridge; the hosts call this when their app backgrounds.
window.PenguinPush={pause(){stopPress();pending=[];audio.pause();},getState(){return{pack:packs[packIndex].id,index,character,theme,...game.snapshot(),sound:audio.enabled,volume:audio.volume};}};
renderer.theme=theme;document.body.dataset.theme=theme;$('theme').value=theme;load(index);selectCharacter(character);soundUI();modal('welcome',true);resizeBoard();
})();
