(function(root){'use strict';
const themes={ice:{sky:'#c7e6f0',snow:'#edf8fb',mountain:'#b3d5e4',floor:'#daedf2',line:'#b6d7e2',wall:'#a5cfe1',wallTop:'#e6f7ff',edge:'#6d9dad'},night:{sky:'#173351',snow:'#7297b6',mountain:'#315877',floor:'#789db8',line:'#63869f',wall:'#567d9d',wallTop:'#bad3e7',edge:'#355874'},wood:{sky:'#bcd9df',snow:'#e9eee6',mountain:'#8daaad',floor:'#e8d3b3',line:'#ccb58e',wall:'#a98463',wallTop:'#d3b089',edge:'#735740'}};
class PenguinRenderer {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.sprite=new Image();this.sprite.src='assets/penguins.png';this.sprite.onload=()=>this.draw(performance.now());this.character=0;this.theme='ice';this.game=null;this.animation=null;this.particles=[];this.raf=null;this.reducedMotion=root.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;}
 setGame(game){this.game=game;this.animation=null;this.particles=[];this.draw(performance.now());}
 animate(event){const now=performance.now();this.animation={...event,start:now,duration:this.reducedMotion?0:event.type==='push'?180:140};if(event.box?.delivered&&!this.reducedMotion){for(let i=0;i<12;i++)this.particles.push({x:event.box.to[0]+.5,y:event.box.to[1]+.5,vx:Math.cos(i*Math.PI/6)*.6,vy:Math.sin(i*Math.PI/6)*.6-.6,start:now,life:600,color:i%2?'#fff2a5':'#56bfa7'});}this.request();}
 celebrate(){if(!this.game||this.reducedMotion)return;const now=performance.now();for(let i=0;i<45;i++)this.particles.push({x:(i*7.13)%this.game.width,y:-1,vx:Math.sin(i)*.5,vy:1+i%3*.2,start:now+i*12,life:1800,color:['#fff','#fff2a5','#6fdfcf','#e97aab'][i%4]});this.request();}
 request(){if(this.raf!==null)return;this.raf=requestAnimationFrame(t=>{this.raf=null;this.draw(t);});}
 draw(now){if(!this.game)return;const ctx=this.ctx,game=this.game,theme=this.theme,t=themes[theme]||themes.ice;const height=this.canvas.height;ctx.clearRect(0,0,900,height);
function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill()}
function fish(x,y,s){ctx.save();ctx.translate(x,y);ctx.rotate(-.18);ctx.fillStyle='#97bdc8';ctx.strokeStyle='#3f7386';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-s*.28,0);ctx.lineTo(-s*.45,-s*.15);ctx.lineTo(-s*.45,s*.15);ctx.closePath();ctx.fill();ctx.stroke();ellipse(0,0,s*.3,s*.13,'#c0dde2');ctx.beginPath();ctx.ellipse(0,0,s*.3,s*.13,0,0,Math.PI*2);ctx.stroke();ellipse(s*.16,-s*.025,s*.027,s*.027,'#274854');ctx.restore()}
function scenery(t){ctx.save();ctx.scale(1,height/660);let grad=ctx.createLinearGradient(0,0,0,660);grad.addColorStop(0,t.sky);grad.addColorStop(1,t.snow);ctx.fillStyle=grad;ctx.fillRect(0,0,900,660);if(theme==='night'){ellipse(755,72,24,24,'#fff1c0');for(let i=0;i<35;i++){ctx.fillStyle='#d7efff';ctx.fillRect((i*137+19)%900,(i*37)%165,2,2)}}else{ellipse(762,65,25,25,'#fff7cf');ellipse(116,61,38,10,'#ffffff88');ellipse(155,58,38,13,'#ffffff88')}ctx.fillStyle=t.mountain;ctx.beginPath();ctx.moveTo(0,180);ctx.lineTo(90,75);ctx.lineTo(190,169);ctx.lineTo(308,99);ctx.lineTo(420,175);ctx.lineTo(550,77);ctx.lineTo(690,166);ctx.lineTo(813,107);ctx.lineTo(900,173);ctx.lineTo(900,300);ctx.lineTo(0,300);ctx.fill();ellipse(450,615,650,370,t.snow);
 if(theme==='wood'){round(720,145,130,90,5,'#bb9171','#765c4a');ctx.fillStyle='#725a4c';ctx.beginPath();ctx.moveTo(705,148);ctx.lineTo(785,99);ctx.lineTo(865,148);ctx.fill();round(770,186,30,49,4,'#4c5156');round(730,164,28,25,2,'#c7e7ec')}else{ctx.save();ctx.translate(773,181);ctx.fillStyle=theme==='night'?'#cadfed':'#f6fdff';ctx.beginPath();ctx.arc(0,0,65,Math.PI,0);ctx.lineTo(-65,0);ctx.fill();ctx.strokeStyle=t.line;ctx.lineWidth=2;ctx.stroke();for(let y=-45;y<0;y+=15){ctx.beginPath();ctx.moveTo(-Math.sqrt(65*65-y*y),y);ctx.lineTo(Math.sqrt(65*65-y*y),y);ctx.stroke()}round(-22,-29,44,34,18,t.edge);ctx.restore()}
 for(let i=0;i<22;i++){let x=(i*167+21)%900,y=200+(i*97)%400;ctx.strokeStyle=theme==='night'?'#bbd8e655':'#b5d6e566';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+12,y-3);ctx.stroke()}ctx.restore()}

scenery(t);
const size=Math.min(120,860/game.width,(height-60)/game.height),ox=(900-size*game.width)/2,oy=(height-size*game.height)/2;
round(ox-12,oy-8,game.width*size+24,game.height*size+27,16,'#284f6822');
for(let y=0;y<game.height;y++)for(let x=0;x<game.width;x++){
 const k=x+','+y,px=ox+x*size,py=oy+y*size;
 if(game.floor.has(k)){round(px,py,size,size,2,t.floor,t.line);ctx.strokeStyle='#ffffff44';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px+size*.15,py+size*.8);ctx.lineTo(px+size*.45,py+size*.74);ctx.stroke();if(game.goals.has(k)){ellipse(px+size/2,py+size/2,size*.29,size*.29,'#fef5ce');ctx.strokeStyle='#d49d3c';ctx.lineWidth=1.5;ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(px+size/2,py+size/2,size*.29,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);fish(px+size*.5,py+size*.5,size*.6);}}
 if(game.walls.has(k)){round(px+.7,py+5,size-1.4,size-1,Math.min(4,size*.1),t.edge);round(px+.7,py-1,size-1.4,size-7,Math.min(4,size*.1),t.wall,t.edge);round(px+2,py-3,size-4,size*.18,3,t.wallTop);ctx.strokeStyle=t.edge+'66';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px+2,py+size*.5);ctx.lineTo(px+size-2,py+size*.5);ctx.moveTo(px+size*.5,py+size*.18);ctx.lineTo(px+size*.5,py+size*.5);ctx.stroke();}
}
let a=this.animation,ratio=a&&a.duration?Math.min(1,Math.max(0,(now-a.start)/a.duration)):1,ease=ratio*ratio*(3-2*ratio),lerp=(v,w)=>v+(w-v)*ease;
if(ratio===1)this.animation=null;
for(const k of game.boxes){let[x,y]=k.split(',').map(Number);if(a?.box&&k===a.box.to.join(',')){x=lerp(a.box.from[0],a.box.to[0]);y=lerp(a.box.from[1],a.box.to[1]);}const px=ox+x*size,py=oy+y*size,ok=game.goals.has(k)&&(!a?.box||k!==a.box.to.join(',')||ratio>.85);
 ellipse(px+size*.5,py+size*.88,size*.38,size*.10,'#23475c33');round(px+size*.1,py+size*.2,size*.8,size*.66,4,ok?'#92bf9e':'#bf9565',ok?'#49775b':'#765536');round(px+size*.1,py+size*.12,size*.8,size*.56,4,ok?'#d6ecd3':'#efd3a1',ok?'#49775b':'#8b633d');ctx.strokeStyle=ok?'#82af86':'#c39763';ctx.lineWidth=1.5;ctx.strokeRect(px+size*.18,py+size*.2,size*.64,size*.4);fish(px+size*.5,py+size*.4,size*.73);if(ok){ctx.fillStyle='#fff';ctx.font=`bold ${size*.22}px system-ui`;ctx.fillText('✓',px+size*.67,py+size*.82);}}
let[x,y]=game.player;if(a?.from&&a?.to){x=lerp(a.from[0],a.to[0]);y=lerp(a.from[1],a.to[1]);}const px=ox+x*size,py=oy+y*size;
ellipse(px+size*.5,py+size*.93,size*.32,size*.09,'#25435644');
if(this.sprite.complete&&this.sprite.naturalWidth){const sw=this.sprite.naturalWidth/4,sh=this.sprite.naturalHeight/2,walking=a&&ratio<1,bob=walking?Math.sin(ratio*Math.PI)*size*.22:0,tilt=walking?Math.sin(ratio*Math.PI*2)*.09:0;ctx.save();ctx.translate(px+size*.5,py+size*.5-bob);ctx.rotate(tilt);ctx.scale(1,walking?1-Math.sin(ratio*Math.PI)*.025:1);ctx.drawImage(this.sprite,game.direction*sw,this.character*sh,sw,sh,-size*.64,-size*.7,size*1.28,size*1.28);ctx.restore();}
this.particles=this.particles.filter(p=>now-p.start<p.life);for(const p of this.particles){const dt=(now-p.start)/1000;if(dt<0)continue;const alpha=Math.max(0,1-(now-p.start)/p.life);ctx.globalAlpha=alpha;ellipse(ox+(p.x+p.vx*dt)*size,oy+(p.y+p.vy*dt+dt*dt*.65)*size,size*.06,size*.06,p.color);}ctx.globalAlpha=1;
ctx.fillStyle=theme==='night'?'#d4e9f8':'#638a9b';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(theme==='wood'?'CABAÑA DE PESCA':'ALMACÉN DEL IGLÚ',450,height-10);ctx.textAlign='left';if(this.animation||this.particles.length)this.request();
 }
}
root.PenguinRenderer=PenguinRenderer;
})(typeof globalThis!=='undefined'?globalThis:this);
